use carsales;

CREATE TABLE BUYER
(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
"NAME" VARCHAR(50) NOT NULL, 
SUTNAME VARCHAR(50) NOT NULL, 
SUTFNAME VARCHAR(50) NOT NULL,
PASSPORT_DATE VARCHAR(50), 
ADRESS VARCHAR(50), 
CITY VARCHAR(50), 
AGE INT,
POL VARCHAR(2),
CHECK(POL IN('Ж', 'М', 'ж', 'М'))
);

CREATE TABLE EMPLOYEE
(
ID INT IDENTITY(1,1) PRIMARY KEY,
"NAME" VARCHAR(50) NOT NULL, 
SUTNAME VARCHAR(50) NOT NULL, 
SUTFNAME VARCHAR(50) NOT NULL,
EXPERIENCE INT DEFAULT 0,
SALARY DECIMAL,
CHECK(EXPERIENCE>0 AND EXPERIENCE<100),
CHECK(SALARY>0)
);

CREATE TABLE CARBRAND
(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
"NAME" VARCHAR(50) NOT NULL, 
ADRESS VARCHAR(50), 
COUNTRY VARCHAR(50), 
FACTORY VARCHAR(50)
);

CREATE TABLE CAR
(
ID INT IDENTITY(1,1) PRIMARY KEY,
KOD_CARBRAND INT,
"NAME" VARCHAR(50),
PRICE DECIMAL,
"YEAR" INT,
COLOR VARCHAR(50),
CATEGORY VARCHAR(50),
CONSTRAINT fk_car_carbrand FOREIGN KEY(KOD_CARBRAND) REFERENCES CARBRAND
);

CREATE TABLE CARSALE
(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
DATESALE DATETIME NOT NULL, 
KOD_CAR INT,
KOD_EMPLOYEE INT,
KOD_BUYER INT,
KOD_CARBRAND INT, 
CONSTRAINT fk_carsale_car FOREIGN KEY(KOD_CAR) REFERENCES CAR,
CONSTRAINT fk_carsale_employee FOREIGN KEY(KOD_EMPLOYEE) REFERENCES EMPLOYEE,
CONSTRAINT fk_carsale_buyer FOREIGN KEY(KOD_BUYER) REFERENCES BUYER,
CONSTRAINT fk_carsale_carbrand FOREIGN KEY(KOD_CARBRAND) REFERENCES CARBRAND
);