use university;
GO

CREATE TABLE KAFEDRA
(
KAFEDRA_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL
)

CREATE TABLE STUDENT
(
STUDENT_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
SUTNAME VARCHAR(50) NOT NULL, 
SUTFNAME VARCHAR(50) NOT NULL,
STIPEND	DECIMAL,
KURS INT,
CITY VARCHAR(50), 
BIRTHDAY DATETIME,
"GROUP" VARCHAR(50),
KOD_KAFEDRU INT,
CHECK(STIPEND<500),
CHECK(KURS>=1 AND KURS<=4),
CONSTRAINT fk_teacher_kafedru FOREIGN KEY(KOD_KAFEDRU) REFERENCES KAFEDRA
);

CREATE TABLE TEACHER
(
KOD_TEACHER INT IDENTITY(1,1) PRIMARY KEY,
KOD_KAFEDRU INT UNIQUE,
NAME_TEACHER VARCHAR(50),
INDEF_KOD INT UNIQUE, ---NOT FOR REPLICATION,
DOLGNOST VARCHAR(50) DEFAULT 'ассистент',
ZVANIE VARCHAR(8) DEFAULT 'нет',
SALARY DECIMAL DEFAULT 1000, 
RISE DECIMAL DEFAULT 0,
DATA_HIRE DATETIME DEFAULT getdate(),
BIRTHDAY DATE,
POL VARCHAR(2),
TEL_TEACHER VARCHAR(50),
CHECK(DOLGNOST IN('профессор', 'доцент', 'старший преподаватель', 'ассистент')),
CHECK(ZVANIE IN('к.т.н', 'к.г.у', 'к.с.н', 'к.ф.м.н.', 'д.т.н', 'д.г.у', 'д.с.н', 'д.ф.м.н', 'нет')),
CHECK(SALARY>0),
CHECK(POL IN('ж', 'Ж', 'м', 'М')),
CHECK(TEL_TEACHER LIKE '[1-9][0-9]- [0-9][0-9]-[0-9][0-9]'),
CHECK (RISE>=0),
CONSTRAINT fk_teacher_kafedru FOREIGN KEY(KOD_KAFEDRU) REFERENCES KAFEDRA
);